# Generated by Django 4.0.2 on 2022-10-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_weight', models.FloatField()),
                ('product_price', models.FloatField()),
            ],
        ),
    ]
