# Generated by Django 4.0.2 on 2022-10-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
